### ISSUE TITLE
Cant find confuguration page?

### ISSUE THREAD

**Issue by Fearofthedark66** [code-debug228/HostetskiGPT#10]
I am on the latest version but cant find the configurationpage?

Module is active but no where to be seen?

**Comment by code-debug228** [comment]
Hello. You can find the module configuration page in the mailbox settings. Please note that you need to have an administrator role to see this page. Tell me which browser you are using. I doubt the problem could be related to this, but I'll check)

**Comment by code-debug228** [comment]
Hello. I think the instructions here will help you #13

**Comment by Fearofthedark66** [comment]
Hi, sorry - that didnt fix the issue as well.

I can only see the module and activate / deactivate it.
