### ISSUE TITLE
Error: max_token to be integer

### ISSUE THREAD

**Issue by dabesa** [code-debug228/HostetskiGPT#14]
Hello guys,
I just installed, activated and configured the plugin, but when I click on "Generate answer (GPT)" I get this:
"Error occurred. Please check your internet connection and try again."

In the Laravel logs I see this error:

" _Type error: Invalid type: expected `Tectalic\OpenAi\Models\ChatCompletions\CreateRequest::max_tokens` to be of type `integer`, instead got value `1024`, which is string._ "

I tried lover numbers (I use gpt3.5) but it's the same.

Is it a bug?

Thanks

**Comment by AliakseyM** [comment]
Hello,

Go to the module settings page and make sure that the value of Token limit is 1024 and does not contain spaces.
Click save and try again.

**Comment by dabesa** [comment]
Hello,

I tried but it doesn't help.
I'm running PHP 8.1, maybe is something related to that?


Thanks

‌


Il giorno mar 6 giu 2023 alle ore 14:25 AliakseyM ***@***.***>
ha scritto:

**Comment by code-debug228** [comment]
Hello, 
What FreeScout version are you using?

**Comment by dabesa** [comment]
I am on latest version of FreeScout and modules are updated.

**Comment by code-debug228** [comment]
Unfortunately, I couldn't reproduce this error, but I made an update in the code that might help. Download updated module code and try again.

**Comment by dabesa** [comment]
Thank you, problem solved!!
