### ISSUE TITLE
Start Message cuts off after saving

### ISSUE THREAD

**Issue by fit4web** [code-debug228/HostetskiGPT#16]
Dear Michail, 

when I enter a longer Start message, as I need to cover different approaches for different problems I figured out that the „Start Message“ field cuts off the last part of my Message. It seams the field has a limitation activated. 

Kind regards and thank you so much for helping me and others so fast in the past.

**Comment by code-debug228** [comment]
Hello,
How many characters are in your start message? What version of the module are you using? In version 1.0.2 there was a limit of about 200 characters, in version 1.0.3 the limit was increased to several tens of thousands of characters.

**Comment by fit4web** [comment]
my mistake then. I thought that the Module overview page will inform me when there is a new version and so I thought it is the most actual version that I have installed.

**Comment by AliakseyM** [comment]
For unofficial modules, FreeScout not have built-in functionality for automatic updates to the latest version or notifications about updates. Please subscribe to the module's GitHub page to stay informed about the latest updates.
