### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by freescout-helpdesk** [code-debug228/HostetskiGPT#2]
FYI. In order the module to work when `APP_PROXY` option is set in .env file the following code need to be applied:

```
        curl_setopt($ch, CURLOPT_TIMEOUT, config('app.curl_timeout'));
        curl_setopt($ch, CURLOPT_PROXY, config('app.proxy'));
```

…or with Guzzle:
```
        $client = new \GuzzleHttp\Client();
        $client->request('POST', $url, [
                'form_params' => $params,
                'timeout' => config('app.curl_timeout'), // add this
                'connect_timeout' => config('app.curl_connect_timeout'), // this
                'proxy' => config('app.proxy'), // and this
        ]);
```

**Comment by code-debug228** [comment]
Thanks, I added those settings. But I have one question, how can I set curl_connect_timeout? I thought it could be done with .env file, but after looking in config/app.php(https://github.com/freescout-helpdesk/freescout/blob/dist/config/app.php) I realized that it couldn't. Maybe I misunderstood something?

**Comment by freescout-helpdesk** [comment]
It will be possible in the next FreeScout release via `APP_CURL_CONNECTION_TIMEOUT` .env variable.

**Comment by code-debug228** [comment]
OK, thanks for your contribution.
