### ISSUE TITLE
Cannot Activate on Postgres

### ISSUE THREAD

**Issue by satsangswami** [code-debug228/HostetskiGPT#20]
Version 1.0.3
FreeScout Version: 1.8.80

SQLSTATE[23502]: Not null violation: 7 ERROR: column "chatgpt" of relation "threads" contains null values (SQL: alter table "threads" add column "chatgpt" text not null) {"userId":9,"email":"nishit.karkar@gurukul.org","exception":"[object] (Illuminate\\Database\\QueryException(code: 23502): SQLSTATE[23502]: Not null violation: 7 ERROR: column \"chatgpt\" of relation \"threads\" contains null values (SQL: alter table \"threads\" add column \"chatgpt\" text not null) at /var/www/html/help.gurukul.org/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 23502): SQLSTATE[23502]: Not null violation: 7 ERROR: column \"chatgpt\" of relation \"threads\" contains null values at /var/www/html/help.gurukul.org/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 23502): SQLSTATE[23502]: Not null violation: 7 ERROR: column \"chatgpt\" of relation \"threads\" contains null values at /var/www/html/help.gurukul.org/overrides/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:115)

**Comment by code-debug228** [comment]
Hello, thanks for your bug report, this error should be fixed in commit d82da81. Upload the updated module code to your FreeScout server and try to activate the module again.
