### ISSUE TITLE
Internet Connection Error

### ISSUE THREAD

**Issue by mahakala** [code-debug228/HostetskiGPT#21]
Hi,
when trying to get a response over GPT, I get error message no connection possible, please check your internet connection.
any hint what is blocked?

Hi,
when trying to get a response over GPT, I get error message no connection possible, please check your internet connection.
any hint what is blocked?

Unsuccessful response. HTTP status code: Array
(
    [Date] => Array
        (
            [0] => Tue, 11 Jul 2023 08:10:19 GMT
        )

    [Content-Type] => Array
        (
            [0] => application/json; charset=utf-8
        )

    [Content-Length] => Array
        (
            [0] => 179
        )

    [Connection] => Array
        (
            [0] => keep-alive
        )

    [vary] => Array
        (
            [0] => Origin
        )

    [x-request-id] => Array
        (
            [0] => c0a4d018f81b87b7c7a3372422f5726c
        )

    [strict-transport-security] => Array
        (
            [0] => max-age=15724800; includeSubDomains
        )

    [CF-Cache-Status] => Array
        (
            [0] => DYNAMIC
        )

    [Server] => Array
        (
            [0] => cloudflare
        )

    [CF-RAY] => Array
        (
            [0] => 7e4f91c08c4d9b80-FRA
        )

    [alt-svc] => Array
        (
            [0] => h3=":443"; ma=86400
        )

)
 404 (Not Found). {"userId":1,"email":"xxx.yyy@xxx.de","exception":"[object] (Tectalic\\OpenAi\\ClientException(code: 0): Unsuccessful response. HTTP status code: Array
(
    [Date] => Array
        (
            [0] => Tue, 11 Jul 2023 08:10:19 GMT
        )

    [Content-Type] => Array
        (
            [0] => application/json; charset=utf-8
        )

    [Content-Length] => Array
        (
            [0] => 179
        )

    [Connection] => Array
        (
            [0] => keep-alive
        )

    [vary] => Array
        (
            [0] => Origin
        )

    [x-request-id] => Array
        (
            [0] => c0a4d018f81b87b7c7a3372422f5726c
        )

    [strict-transport-security] => Array
        (
            [0] => max-age=15724800; includeSubDomains
        )

    [CF-Cache-Status] => Array
        (
            [0] => DYNAMIC
        )

    [Server] => Array
        (
            [0] => cloudflare
        )

    [CF-RAY] => Array
        (
            [0] => 7e4f91c08c4d9b80-FRA
        )

    [alt-svc] => Array
        (
            [0] => h3=\":443\"; ma=86400
        )

)
 404 (Not Found). at /usr/www/users/xxxx/intern/tickets/Modules/HostetskiGPT/vendor/tectalic/openai/src/Handlers/ChatCompletions.php:150)
[stacktrace]
#0 /usr/www/users/xxxx/intern/tickets/Modules/HostetskiGPT/Http/Controllers/HostetskiGPTController.php(120): Tectalic\\OpenAi\\Handlers\\ChatCompletions->toModel()
#1 [internal function]: Modules\\HostetskiGPT\\Http\\Controllers\\HostetskiGPTController->generate()
#2 /usr/www/users/xxxx/intern/tickets/overrides/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array()
#3 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#4 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Routing/Route.php(211): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#5 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#6 /usr/www/users/xxxx/intern/tickets/overrides/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Route->run()
#7 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#8 /usr/www/users/xxxx/intern/tickets/app/Http/Middleware/CustomHandle.php(22): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#9 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\CustomHandle->handle()
#10 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#11 /usr/www/users/xxxx/intern/tickets/app/Http/Middleware/LogoutIfDeleted.php(28): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#12 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\LogoutIfDeleted->handle()
#13 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /usr/www/users/xxxx/intern/tickets/app/Http/Middleware/Localize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#15 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\Localize->handle()
#16 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /usr/www/users/xxxx/intern/tickets/app/Http/Middleware/HttpsRedirect.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#18 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\HttpsRedirect->handle()
#19 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#21 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#22 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(67): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#24 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#25 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#27 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#28 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /usr/www/users/xxxx/intern/tickets/app/Http/Middleware/TokenAuth.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#30 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\TokenAuth->handle()
#31 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#33 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Session\\Middleware\\StartSession->handle()
#34 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#36 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#37 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#39 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#40 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#42 /usr/www/users/xxxx/intern/tickets/overrides/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\\Pipeline\\Pipeline->then()
#43 /usr/www/users/xxxx/intern/tickets/overrides/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\\Routing\\Router->runRouteWithinStack()
#44 /usr/www/users/xxxx/intern/tickets/overrides/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\\Routing\\Router->runRoute()
#45 /usr/www/users/xxxx/intern/tickets/overrides/laravel/framework/src/Illuminate/Routing/Router.php(590): Illuminate\\Routing\\Router->dispatchToRoute()
#46 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch()
#47 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#48 /usr/www/users/xxxx/intern/tickets/app/Http/Middleware/TerminateHandler.php(12): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#49 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\TerminateHandler->handle()
#50 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 /usr/www/users/xxxx/intern/tickets/app/Http/Middleware/ResponseHeaders.php(11): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#52 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\ResponseHeaders->handle()
#53 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 /usr/www/users/xxxx/intern/tickets/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#55 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Fideloper\\Proxy\\TrustProxies->handle()
#56 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#58 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#59 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#60 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#61 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#62 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#63 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#64 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#65 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#66 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#67 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#68 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#69 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#70 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then()
#71 /usr/www/users/xxxx/intern/tickets/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#72 /usr/www/users/xxxx/intern/tickets/public/index.php(82): Illuminate\\Foundation\\Http\\Kernel->handle()
#73 {main}
"}

**Comment by code-debug228** [comment]
Hello. No, your email is not sent anywhere, FreeScout just outputs error logs indicating which user had this error. What GPT model is selected in your module settings? If gpt-4, then try to select gpt-3.5-turbo.

**Comment by mahakala** [comment]
Thanks. Tried all available settings - always same result. 🤷‍♀️

**Comment by code-debug228** [comment]
When requesting /hostetskigpt/generate, if any error occurs, there will always be a 500 http code. You can see the detailed error message only in the FreeScout logs.
I've only seen 404 errors when making requests to the gpt-4 model when the account doesn't have access to it. When you select the gpt-3.5-turbo model, does the same 404 error appear in the FreeScout logs or some other?

**Comment by mahakala** [comment]
Thanks for your help. I guess Cloudflare rejects now with 429 and i'm requesting too much. well - every 5 minutes a try isn't so nasty.

**Comment by code-debug228** [comment]
Your email is not used for API requests. Authorization in their API works using the API key, which you specify in the module settings.
Please send an email to support@cloudcenter.ovh so that we can provide you with a test OpenAI key. This will help us understand if it's a problem with the module or with your OpenAI account settings.
