### ISSUE TITLE
Freescout will not work after Installation of Module

### ISSUE THREAD

**Issue by szucher** [code-debug228/HostetskiGPT#22]
Hi,

i have a problem. After unzip the file and upload the files to the module Folder in Freescout i get an errror page! Freescout will not working anymore. I get: "Whoops, looks like something went wrong — check logs in /storage/logs"

`[2023-07-14 07:51:49] production.ERROR: Class "Modules\HostetskiGPT\Providers\HostetskiGPTServiceProvider" not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class \"Modules\\HostetskiGPT\\Providers\\HostetskiGPTServiceProvider\" not found at /www/htdocs/w01598d5/mail.zucher-duingen.de/overrides/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:279)
[stacktrace]
#0 /www/htdocs/w01598d5/mail.zucher-duingen.de/overrides/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(189): Illuminate\\Foundation\\ProviderRepository->createProvider('Modules\\\\Hostets...')
#1 /www/htdocs/w01598d5/mail.zucher-duingen.de/overrides/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(70): Illuminate\\Foundation\\ProviderRepository->compileManifest(Array)
#2 /www/htdocs/w01598d5/mail.zucher-duingen.de/vendor/nwidart/laravel-modules/src/Laravel/Module.php(27): Illuminate\\Foundation\\ProviderRepository->load(Array)
#3 /www/htdocs/w01598d5/mail.zucher-duingen.de/overrides/nwidart/laravel-modules/src/Module.php(279): Nwidart\\Modules\\Laravel\\Module->registerProviders()
#4 /www/htdocs/w01598d5/mail.zucher-duingen.de/overrides/nwidart/laravel-modules/src/Repository.php(366): Nwidart\\Modules\\Module->register()
#5 /www/htdocs/w01598d5/mail.zucher-duingen.de/vendor/nwidart/laravel-modules/src/Providers/BootstrapServiceProvider.php(22): Nwidart\\Modules\\Repository->register()
#6 /www/htdocs/w01598d5/mail.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(586): Nwidart\\Modules\\Providers\\BootstrapServiceProvider->register()
#7 /www/htdocs/w01598d5/mail.zucher-duingen.de/vendor/nwidart/laravel-modules/src/ModulesServiceProvider.php(38): Illuminate\\Foundation\\Application->register(Object(Nwidart\\Modules\\Providers\\BootstrapServiceProvider))
#8 /www/htdocs/w01598d5/mail.zucher-duingen.de/vendor/nwidart/laravel-modules/src/LaravelModulesServiceProvider.php(15): Nwidart\\Modules\\ModulesServiceProvider->registerModules()
#9 [internal function]: Nwidart\\Modules\\LaravelModulesServiceProvider->boot()
#10 /www/htdocs/w01598d5/mail.zucher-duingen.de/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#11 /www/htdocs/w01598d5/mail.zucher-duingen.de/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#12 /www/htdocs/w01598d5/mail.zucher-duingen.de/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#13 /www/htdocs/w01598d5/mail.zucher-duingen.de/overrides/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#14 /www/htdocs/w01598d5/mail.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(792): Illuminate\\Container\\Container->call(Array)
#15 /www/htdocs/w01598d5/mail.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\\Foundation\\Application->bootProvider(Object(Nwidart\\Modules\\LaravelModulesServiceProvider))
#16 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(Nwidart\\Modules\\LaravelModulesServiceProvider), 22)
#17 /www/htdocs/w01598d5/mail.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(776): array_walk(Array, Object(Closure))
#18 /www/htdocs/w01598d5/mail.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#19 /www/htdocs/w01598d5/mail.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(213): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#20 /www/htdocs/w01598d5/mail.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(162): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#21 /www/htdocs/w01598d5/mail.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(146): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#22 /www/htdocs/w01598d5/mail.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#23 /www/htdocs/w01598d5/mail.zucher-duingen.de/public/index.php(83): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#24 {main}
"} 
[2023-07-14 07:51:54] production.ERROR: Class "Modules\HostetskiGPT\Providers\HostetskiGPTServiceProvider" not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class \"Modules\\HostetskiGPT\\Providers\\HostetskiGPTServiceProvider\" not found at /www/htdocs/w01598d5/mail.zucher-duingen.de/overrides/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:279)
[stacktrace]
#0 /www/htdocs/w01598d5/mail.zucher-duingen.de/overrides/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(189): Illuminate\\Foundation\\ProviderRepository->createProvider('Modules\\\\Hostets...')
#1 /www/htdocs/w01598d5/mail.zucher-duingen.de/overrides/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(70): Illuminate\\Foundation\\ProviderRepository->compileManifest(Array)
#2 /www/htdocs/w01598d5/mail.zucher-duingen.de/vendor/nwidart/laravel-modules/src/Laravel/Module.php(27): Illuminate\\Foundation\\ProviderRepository->load(Array)
#3 /www/htdocs/w01598d5/mail.zucher-duingen.de/overrides/nwidart/laravel-modules/src/Module.php(279): Nwidart\\Modules\\Laravel\\Module->registerProviders()
#4 /www/htdocs/w01598d5/mail.zucher-duingen.de/overrides/nwidart/laravel-modules/src/Repository.php(366): Nwidart\\Modules\\Module->register()
#5 /www/htdocs/w01598d5/mail.zucher-duingen.de/vendor/nwidart/laravel-modules/src/Providers/BootstrapServiceProvider.php(22): Nwidart\\Modules\\Repository->register()
#6 /www/htdocs/w01598d5/mail.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(586): Nwidart\\Modules\\Providers\\BootstrapServiceProvider->register()
#7 /www/htdocs/w01598d5/mail.zucher-duingen.de/vendor/nwidart/laravel-modules/src/ModulesServiceProvider.php(38): Illuminate\\Foundation\\Application->register(Object(Nwidart\\Modules\\Providers\\BootstrapServiceProvider))
#8 /www/htdocs/w01598d5/mail.zucher-duingen.de/vendor/nwidart/laravel-modules/src/LaravelModulesServiceProvider.php(15): Nwidart\\Modules\\ModulesServiceProvider->registerModules()
#9 [internal function]: Nwidart\\Modules\\LaravelModulesServiceProvider->boot()
#10 /www/htdocs/w01598d5/mail.zucher-duingen.de/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#11 /www/htdocs/w01598d5/mail.zucher-duingen.de/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#12 /www/htdocs/w01598d5/mail.zucher-duingen.de/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#13 /www/htdocs/w01598d5/mail.zucher-duingen.de/overrides/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#14 /www/htdocs/w01598d5/mail.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(792): Illuminate\\Container\\Container->call(Array)
#15 /www/htdocs/w01598d5/mail.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\\Foundation\\Application->bootProvider(Object(Nwidart\\Modules\\LaravelModulesServiceProvider))
#16 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(Nwidart\\Modules\\LaravelModulesServiceProvider), 22)
#17 /www/htdocs/w01598d5/mail.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(776): array_walk(Array, Object(Closure))
#18 /www/htdocs/w01598d5/mail.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#19 /www/htdocs/w01598d5/mail.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(213): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#20 /www/htdocs/w01598d5/mail.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(162): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#21 /www/htdocs/w01598d5/mail.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(146): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#22 /www/htdocs/w01598d5/mail.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#23 /www/htdocs/w01598d5/mail.zucher-duingen.de/public/index.php(83): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#24 {main}
"} 
`

**Comment by code-debug228** [comment]
Hello, how did you name the folder with the module? It should be named HostetskiGPT, not, for example, hostetskigpt or Hostetskigpt.

**Comment by szucher** [comment]
Now Freescout works, it was the Name of the folder. But when i try to get a answer from chatgpt, freescout says there is no available internet connection

**Comment by code-debug228** [comment]
Open in FreeScout Manage -> Logs -> App Logs and open laravel-{todaydate}.log file. There will be a more detailed error. Most likely the problem is that the wrong GPT model is selected in the module settings (gpt-4 is selected, but you do not have access to it) or there are some problems with the settings in your OpenAI account.
