### ISSUE TITLE
"HostetskiGPT" doesn't appears in the settings menu

### ISSUE THREAD

**Issue by noxonsu** [code-debug228/HostetskiGPT#23]
1. i have instlalled and activated module 
2. go to "Mainlbox -> Settings"

"HostetskiGPT" doesn't appears in the left menu

![image](https://github.com/code-debug228/HostetskiGPT/assets/2914674/367c783e-d5ad-4011-af21-82f01bf577e5)

system: 

![image](https://github.com/code-debug228/HostetskiGPT/assets/2914674/9e257ee8-ced8-4aa1-a00a-d880a09928d1)

**Comment by invmedia** [comment]
I agree with the post. I have the same problem. Do you have any solution?

**Comment by code-debug228** [comment]
Is the module folder named HostetskiGPT? There should be just such a name, and not, for example, hostetskigpt.

**Comment by noxonsu** [comment]
this helps https://github.com/code-debug228/HostetskiGPT/issues/13

**Comment by invmedia** [comment]
Actually, I had a folder called "HostetskiGPT-main". I deactivated the application, deleted it. I uploaded it again to the server. I unpacked it, changed the name to "HostetskiGPT", deleted the file: "hostetski_g_p_t_module.php". I activated the chat, it still doesn't work. Do you have any other ideas what I'm doing wrong?
