### ISSUE TITLE
Not working / Not displaying anything

### ISSUE THREAD

**Issue by adrianrss** [code-debug228/HostetskiGPT#4]
Hi there,

I just tried the module on Freescout [1.8.69] and it doesn't seem to work at all. I've added my API Key in the configuration file, I've enabled the plugin, didn't get any errors at all but the plugin is not working.
On every ticket I go, it doesn't show any reply suggestion, it doesn't show anything like the plugin is not even enabled.

Does this plugin need a newer Freescout version? We currently have a lot of customizations on 1.8.69 so it's a bit tricky to update...

**Comment by code-debug228** [comment]
Hello. Do you click the button Generate answer(ChatGPT) in the dropdown next to the message? Also now we found out that the module does not work correctly in some browsers (see issue #1), we will fix it soon.

**Comment by code-debug228** [comment]
Did you clone the repository to the HostetskiGPT folder or some other folder(hostetskigpt, hostetskiGPT, etc.)? If not, try placing the module exactly in the HostetskiGPT folder. A bit later I’ll add information about it in the README.

**Comment by code-debug228** [comment]
Are there any errors in the Freescout logs(file laravel-[date].log) or in browser console in developer tools?

**Comment by AliakseyM** [comment]
Did it work for you in version 1.0.1? https://github.com/code-debug228/HostetskiGPT/releases/tag/bugfix
By the way, GPT button located in dropdown menu (near info about time and status for comment), in your screenshot, you are looking for a button in the form for adding a comment

**Comment by code-debug228** [comment]
Could you try using some another API key? During development, I also encountered such an error, but after changing the key to another one, everything worked and continues to work until now.

**Comment by code-debug228** [comment]
Do you use the free version of OpenAI API? If so, your free trial may have expired. You can read more about it for example here: https://github.com/TheR1D/shell_gpt/issues/75
Or perhaps you have set too low usage limits in your OpenAI account.
