### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by adrianrss** [code-debug228/HostetskiGPT#5]
Could you add a spinning wheel or "Loading ChatGPT" message until the message actually appears? It's a bit confusing that nothing happens for a few seconds and then it suddenly appears. Would make the UI a bit better :)

Also, is there a way we could feed it a public knowlegebase that we have? Maybe do you have some good prompts or ideas for that?
It would be nice to be able to do this so we can have more accurate answers, not just general ones.

**Comment by AliakseyM** [comment]
About the prompts for generating responses, you can use this information: https://github.com/code-debug228/HostetskiGPT/issues/3#issuecomment-1518681778

**Comment by code-debug228** [comment]
About the spinning wheel: yes, I wanted to do it via default FreeScout loader, but it blocks all other actions on the page, I think that it will not be very convenient. Soon I will add a more convenient loader, which will be displayed next to the message to which GPT reply was requested.
