### ISSUE TITLE
It doesn't work 

### ISSUE THREAD

**Issue by alejandroalmarza** [code-debug228/HostetskiGPT#7]
Hello. First I want to thank you all for your work. 

I am trying to test it but I Can't.

First I used the bugfix version on the releases. It says it activated but it doesn't even show the config tab. then I tryed using the. Note I already set the permisions of the folde to 775

`Error occurred creating a module symlink (/home/idfh2gehq68s/public_html/supportcdg/public/modules/hostetskigpt). Please check folder permissions.

Cache cleared successfully.
Nothing to migrate.
Error occurred creating [/home/idfh2gehq68s/public_html/supportcdg/public/modules/hostetskigpt] symlink: symlink(): No such file or directory
The [/home/idfh2gehq68s/public_html/supportcdg/public/modules/hostetskigpt] symlink has been created
Clearing cache...
The compiled services & packages files have been removed.
Cache cleared successfully.
Compiled views cleared!
Configuration cache cleared!
Configuration cached successfully!
Created: storage/app/public/js/vars.js`

I am using Freescout 1.8.76

**Comment by code-debug228** [comment]
Hello. Sorry, we updated information in the README before we released the update itself :) In version 1.0.1 there were no settings through the web interface, but right now they appeared. Please download actual code from the repository, replace old code with it, re-enable module and try again. After update you can find configuration tab in mailbox settings.

**Comment by AliakseyM** [comment]
Update module to new version https://github.com/code-debug228/HostetskiGPT/releases/tag/1.0.2

**Please note that after the update, you must either turn the module off and on again, or run the command "php artisan migrate" in the fs folder, as the database has been updated.**

**Comment by alejandroalmarza** [comment]
Hello. Thanks for your quick response. I Installed the new version but I don't know why it doesn't activate when I try. I deactivated the module and erased the old package. When I try to activate it, It give me an error mesage. But then I changed the folder name to HostetskiGPT-bugfix and it activate but it doesn't show any sign of being active because nothing change on the site where it should be the config or even when I try to edit a response. 

> Error occurred creating a module symlink (/home/idfh2gehq68s/public_html/supportcdg/public/modules/hostetskigpt). Please check folder permissions.

Please let me know if you need any other information.

**Comment by Sim0nW0lf** [comment]
It looks like your folder permissions are wrong after unpacking?

Try `ls -la` in the module folder. Your HostetskiGPT folder will probably show a different user.

Then `chown your_user:your_group HostetskiGPT -R`. This will change the owner recursively.

For me the new version works fine 👍🏻 Just be sure to use the correct ChatGPT Version. For the free API only 3.5 works I believe. Version 4 said there's no connection to internet.

**Comment by alejandroalmarza** [comment]
> 

thanks fro your response. The issue with the folders name was related to the simlink. The first time I tried to activate the module I simply unpacked the folder and changed the permissions  after I deleted the simlink it generated a new one and corrected. Now it show its activated but it doesn't show any change on freescout so its just like it wasn't active.

**Comment by Sim0nW0lf** [comment]
So you

1. deleted the old module in the freescout settings
2. unpacked the new module
3. changed name/permissions
4. activated the module in the settings

and it's still not working?

**Comment by alejandroalmarza** [comment]
> 

I tried all that and erasing the cache before copying the module again and reactivating it but it still doesn't work.

**Comment by Sim0nW0lf** [comment]
Hmm maybe restart freescout?
