### ISSUE TITLE
Error "No internet Connection"

### ISSUE THREAD

**Issue by AntoWkill** [code-debug228/HostetskiGPT#8]
Hello,

Im trying to use the module without success check error

<img width="1680" alt="Screenshot 2023-05-11 alle 20 15 28" src="https://github.com/code-debug228/HostetskiGPT/assets/21131925/8af44c7f-9bca-428c-a11c-0ed55501ebee">

**Comment by Sim0nW0lf** [comment]
In the settings change ChatGPT Version to 3.5
