### ISSUE TITLE
Unsuccessful response error

### ISSUE THREAD

**Issue by ruess** [code-debug228/HostetskiGPT#9]
Looks like my [other issue ](https://github.com/code-debug228/HostetskiGPT/issues/6) appears to have resolved itself for the time being.

That said, I'm getting a new issue in my logs:
`Unsuccessful response. HTTP status code: 400 (Bad Request). {"userId":1,"email":"[my_email_address]","exception":"[object] (Tectalic\\OpenAi\\ClientException(code: 0): Unsuccessful response. HTTP status code: 400 (Bad Request). at /home/473026.cloudwaysapps.com/hyqtxkhzth/public_html/Modules/HostetskiGPT/vendor/tectalic/openai/src/Handlers/ChatCompletions.php:150) `

Any ideas of what this might be? I'm using a premium API account and have tried both GPT 3.5 and 4 in settings (v1.0.2), both with the same result.

Thanks!

**Comment by MarcoWel** [comment]
429 Too Many Requests for me.

**Comment by ruess** [comment]
Sounds like your 429 might be related to openAI API getting bogged down. Has it started working after a delay and retry?

My issue is similar to the last one I posted, but now an update: it's turned from a 400 (Bad Request) to a 404 (Not Found).
`Unsuccessful response. HTTP status code: 404 (Not Found). {"userId":1,"email":"[my@email_address]","exception":"[object] (Tectalic\\OpenAi\\ClientException(code: 0): Unsuccessful response. HTTP status code: 404 (Not Found). at /home/473026.cloudwaysapps.com/hyqtxkhzth/public_html/Modules/HostetskiGPT/vendor/tectalic/openai/src/Handlers/ChatCompletions.php:150) `

**Comment by ruess** [comment]
Good news update. It's working now that I switched it to GPT 3.5. I had tried that initially but it did not work, even with 3.5, when I created this issue. Maybe it was an overloaded gpt API the first time or something.

**Comment by MarcoWel** [comment]
Worked for me as well now. Reason for 429:
Account needs a payment method after trial expired, and the API key needs to be re-created after the payment method has been added to the account.
